<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe</name>
   <tag></tag>
   <elementGuidId>eb4c74f7-a203-4621-8879-eae985460363</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='credential_picker_container']/iframe</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>iframe[title=&quot;Dialog Login dengan Google&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>f4841b51-269c-4c6b-a37e-7901eb2ae9d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://accounts.google.com/gsi/iframe/select?client_id=776828813358-infk4sje3q07sa8mg8n6lq1mk2pdkkua.apps.googleusercontent.com&amp;auto_select=true&amp;ux_mode=popup&amp;ui_mode=card&amp;as=7c6SXPKwrzSjgb93LoYdBA&amp;is_itp=true&amp;channel_id=927acd86c4e07760a9f92815f2e74d51adf3745b09703a74478f80b566056903&amp;origin=https%3A%2F%2Fwww.kompas.com</value>
      <webElementGuid>b61b6746-806d-49cd-a2ec-ae0e927163cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Dialog Login dengan Google</value>
      <webElementGuid>c442485b-e701-42d3-9be1-592b44787216</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;credential_picker_container&quot;)/iframe[1]</value>
      <webElementGuid>d06be498-f3f4-47cc-b5ab-8e3329deb4d9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='credential_picker_container']/iframe</value>
      <webElementGuid>140765c2-e4fe-448f-afa2-070f637c8fa9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/iframe</value>
      <webElementGuid>3319bf58-dcc3-4ebe-a3e7-db1d068a19cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = 'https://accounts.google.com/gsi/iframe/select?client_id=776828813358-infk4sje3q07sa8mg8n6lq1mk2pdkkua.apps.googleusercontent.com&amp;auto_select=true&amp;ux_mode=popup&amp;ui_mode=card&amp;as=7c6SXPKwrzSjgb93LoYdBA&amp;is_itp=true&amp;channel_id=927acd86c4e07760a9f92815f2e74d51adf3745b09703a74478f80b566056903&amp;origin=https%3A%2F%2Fwww.kompas.com' and @title = 'Dialog Login dengan Google']</value>
      <webElementGuid>ba5e388c-4e91-4550-9fa6-3e5c60637b6c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
