<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>google close</name>
   <tag></tag>
   <elementGuidId>3bcb58af-8a1d-4180-8edc-6753647d70fd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>bee88cec-3957-446b-ba6a-f53a576aaedf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1706201771970</value>
      <webElementGuid>88f9b882-a1f4-47dd-84a2-308ff29551bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>close</value>
      <webElementGuid>131ffb63-0af5-4e8b-ab20-ef5705a4160d</webElementGuid>
   </webElementProperties>
</WebElementEntity>
