<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_google_login</name>
   <tag></tag>
   <elementGuidId>37930d86-3483-4342-80ee-d2b05cb3a656</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='animated-container']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#animated-container</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>3f398f03-0fc0-4850-92f3-efe7cff344f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>animated-container</value>
      <webElementGuid>6bc09fe6-47d8-4beb-8341-ad020c4b6240</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>YLEHIf-haAclf   </value>
      <webElementGuid>65e3af46-0e3b-4137-8200-d7150235aa57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Login dengan GoogleMemverifikasi...Gunakan Akun Google Anda untuk login ke Kompas.comTidak perlu lagi mengingat sandi. Login menjadi cepat, mudah, dan aman.Lanjutkan</value>
      <webElementGuid>0709d769-e4b8-4cb0-8ea8-c41096b30e5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;animated-container&quot;)</value>
      <webElementGuid>86760bf3-815c-4b6c-b059-d4613c9ba70f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='animated-container']</value>
      <webElementGuid>532bed50-3a0b-4c0c-a71a-4326414faed8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='container']/div</value>
      <webElementGuid>09474c00-dc5f-4322-8d8b-8bdc9bbf2460</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div</value>
      <webElementGuid>347a1628-9c87-4245-a7d6-48398032b516</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'animated-container' and (text() = 'Login dengan GoogleMemverifikasi...Gunakan Akun Google Anda untuk login ke Kompas.comTidak perlu lagi mengingat sandi. Login menjadi cepat, mudah, dan aman.Lanjutkan' or . = 'Login dengan GoogleMemverifikasi...Gunakan Akun Google Anda untuk login ke Kompas.comTidak perlu lagi mengingat sandi. Login menjadi cepat, mudah, dan aman.Lanjutkan')]</value>
      <webElementGuid>22c4eb87-1b1c-4a0e-a235-76d2b5accc76</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
