<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Click news (text)</name>
   <tag></tag>
   <elementGuidId>933d2262-1995-4fe9-a77f-7eed7d37c799</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='___gcse_0']/div/div/div/div[5]/div[2]/div/div/div/div[2]/div/div/div/a</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@href = 'https://www.google.com/url?client=internal-element-cse&amp;cx=partner-pub-9012468469771973:uc7pie-r3ad&amp;q=https://nasional.kompas.com/read/2024/01/19/16002521/pbnu-benarkan-temui-pengurus-se-jawa-timur-beri-arahan-soal-pilpres-2024%3Fpage%3Dall&amp;sa=U&amp;ved=2ahUKEwi6gLKri_mDAxXbwTgGHbRSCdwQFnoECAkQAg&amp;usg=AOvVaw3QkuoaUS2JriO9HPBTvOfP']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>5eb535a8-6671-43f8-af59-a24a719d4466</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gs-title</value>
      <webElementGuid>903180f1-c9c3-47f3-9350-7ac14239b077</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.google.com/url?client=internal-element-cse&amp;cx=partner-pub-9012468469771973:uc7pie-r3ad&amp;q=https://nasional.kompas.com/read/2024/01/19/16002521/pbnu-benarkan-temui-pengurus-se-jawa-timur-beri-arahan-soal-pilpres-2024%3Fpage%3Dall&amp;sa=U&amp;ved=2ahUKEwi6gLKri_mDAxXbwTgGHbRSCdwQFnoECAkQAg&amp;usg=AOvVaw3QkuoaUS2JriO9HPBTvOfP</value>
      <webElementGuid>138b41c8-6353-4cc0-9ff1-e2089d7cd6d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_parent</value>
      <webElementGuid>955f06d9-734d-4735-b03c-da136e59c441</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dir</name>
      <type>Main</type>
      <value>ltr</value>
      <webElementGuid>bfe3c753-e1c6-42fd-afd2-adffcba1e727</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-cturl</name>
      <type>Main</type>
      <value>https://www.google.com/url?client=internal-element-cse&amp;cx=partner-pub-9012468469771973:uc7pie-r3ad&amp;q=https://nasional.kompas.com/read/2024/01/19/16002521/pbnu-benarkan-temui-pengurus-se-jawa-timur-beri-arahan-soal-pilpres-2024%3Fpage%3Dall&amp;sa=U&amp;ved=2ahUKEwi6gLKri_mDAxXbwTgGHbRSCdwQFnoECAkQAg&amp;usg=AOvVaw3QkuoaUS2JriO9HPBTvOfP</value>
      <webElementGuid>909c7136-bac8-4292-ac62-fa6abcd36b7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ctorig</name>
      <type>Main</type>
      <value>https://nasional.kompas.com/read/2024/01/19/16002521/pbnu-benarkan-temui-pengurus-se-jawa-timur-beri-arahan-soal-pilpres-2024?page=all</value>
      <webElementGuid>ddc09e52-9f8a-4bbc-9757-60dade816b07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>PBNU Benarkan Temui Pengurus Se-Jawa Timur, Beri Arahan soal ...</value>
      <webElementGuid>b3931438-fd39-4516-b23a-d398f80f9a59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;___gcse_0&quot;)/div[@class=&quot;gsc-control-cse gsc-control-cse-en&quot;]/div[@class=&quot;gsc-control-wrapper-cse&quot;]/div[@class=&quot;gsc-results-wrapper-nooverlay gsc-results-wrapper-visible&quot;]/div[@class=&quot;gsc-wrapper&quot;]/div[@class=&quot;gsc-resultsbox-visible&quot;]/div[@class=&quot;gsc-resultsRoot gsc-tabData gsc-tabdActive&quot;]/div[@class=&quot;gsc-results gsc-webResult&quot;]/div[@class=&quot;gsc-expansionArea&quot;]/div[@class=&quot;gsc-webResult gsc-result&quot;]/div[@class=&quot;gs-webResult gs-result&quot;]/div[@class=&quot;gsc-thumbnail-inside&quot;]/div[@class=&quot;gs-title&quot;]/a[@class=&quot;gs-title&quot;]</value>
      <webElementGuid>4834af30-a53f-4ad1-aa51-ba7c502d653c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='___gcse_0']/div/div/div/div[5]/div[2]/div/div/div/div[2]/div/div/div/a</value>
      <webElementGuid>2eb3367f-4fff-4d47-bd04-9bd94822c3b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='pilpres'])[2]/following::a[1]</value>
      <webElementGuid>4d0ee0ac-28ae-4ab9-8cdc-f74ff7d60bf0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='nasional.kompas.com'])[3]/preceding::a[1]</value>
      <webElementGuid>d41cd6c4-ef59-407a-88ac-1e0265d30c45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='https://nasional.kompas.com/.../pbnu-benarkan-temui-pengurus-se-jawa-tim...'])[1]/preceding::a[1]</value>
      <webElementGuid>99fbd26f-8d2b-4006-8aa1-2feb5cfd112d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.google.com/url?client=internal-element-cse&amp;cx=partner-pub-9012468469771973:uc7pie-r3ad&amp;q=https://nasional.kompas.com/read/2024/01/19/16002521/pbnu-benarkan-temui-pengurus-se-jawa-timur-beri-arahan-soal-pilpres-2024%3Fpage%3Dall&amp;sa=U&amp;ved=2ahUKEwi6gLKri_mDAxXbwTgGHbRSCdwQFnoECAkQAg&amp;usg=AOvVaw3QkuoaUS2JriO9HPBTvOfP')]</value>
      <webElementGuid>e1cfb741-7977-4a77-b31d-7db7f9f32a96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/a</value>
      <webElementGuid>c0966411-8609-4c30-999e-96b04295a75d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.google.com/url?client=internal-element-cse&amp;cx=partner-pub-9012468469771973:uc7pie-r3ad&amp;q=https://nasional.kompas.com/read/2024/01/19/16002521/pbnu-benarkan-temui-pengurus-se-jawa-timur-beri-arahan-soal-pilpres-2024%3Fpage%3Dall&amp;sa=U&amp;ved=2ahUKEwi6gLKri_mDAxXbwTgGHbRSCdwQFnoECAkQAg&amp;usg=AOvVaw3QkuoaUS2JriO9HPBTvOfP' and (text() = 'PBNU Benarkan Temui Pengurus Se-Jawa Timur, Beri Arahan soal ...' or . = 'PBNU Benarkan Temui Pengurus Se-Jawa Timur, Beri Arahan soal ...')]</value>
      <webElementGuid>48046a7d-85b1-4526-b773-b21afc1f1f78</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
